---
name: Text-ECSV
version: 0.01
author:
  - 'Jozef Kutej <jkutej@cpan.org>'
abstract: Extended CSV manipulation routines
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor::Fast: 0
  Text::CSV_XS: 0
build_requires:
  Test::More: 0
provides:
  Text::ECSV:
    file: lib/Text/ECSV.pm
    version: 0.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
